name: darc
description: "DARC provides a minimal yet powerful public HTTP Requests interface while internalizing all the complexity"
version: 0.0.6

homepage: https://github.com/Mohamed-Shalabi/darc
repository: https://github.com/Mohamed-Shalabi/darc
issue_tracker: https://github.com/Mohamed-Shalabi/darc/issues


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  fpdart: ^1.2.0
  fresh_dio: ^0.4.4
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0

